title: Alex Eberle # your name (or website title) here
logo: "/images/profile.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  2+ years experence in the GIS and Environmental field. Recieved a Bachelors from
  the University of Kentucky in Natural Resources and Environmental Science. My concentration
  was in GIS and water resource management. Additionally, I have an Associates of Applied Science
  in Environmental Science Technology from the Kentucky Community and Technical College System.
  <br><br>
  Current Job Title:
  GIS Analyst & Environmental Scientist
  <br><br>
  <a href="https://www.linkedin.com/in/alex-eberle">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
