title: Alex Eberle # your name (or website title) here
logo: "/images/profile.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  2+ years experence in the GIS and Environmental field. 
  <br><br>
  B.S. Natural Resources & Environmental Science from the University of Kentucky
  <br><br>
  Current Job Title:
  GIS Analyst & Environmental Scientist
  <br><br>
  <a href="https://www.linkedin.com/in/alex-eberle">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
